#include "errno.h"

const char *strerrno(int err)
{
	if (err < 0){
		err = -err;
	}
	switch (err){
	case EPERM: return "EPERM";
	case ENOENT: return "ENOENT";
	case ESRCH: return "ESRCH";
	case EINTR: return "EINTR";
	case EIO: return "EIO";
	case ENXIO: return "ENXIO";
	case E2BIG: return "E2BIG";
	case ENOEXEC: return "ENOEXEC";
	case EBADF: return "EBADF";
	case ECHILD: return "ECHILD";
	case EAGAIN: return "EAGAIN";
	case ENOMEM: return "ENOMEM";
	case EACCES: return "EACCES";
	case EFAULT: return "EFAULT";
	case ENOTBLK: return "ENOTBLK";
	case EBUSY: return "EBUSY";
	case EEXIST: return "EEXIST";
	case EXDEV: return "EXDEV";
	case ENODEV: return "ENODEV";
	case ENOTDIR: return "ENOTDIR";
	case EISDIR: return "EISDIR";
	case EINVAL: return "EINVAL";
	case ENFILE: return "ENFILE";
	case EMFILE: return "EMFILE";
	case ENOTTY: return "ENOTTY";
	case ETXTBSY: return "ETXTBSY";
	case EFBIG: return "EFBIG";
	case ENOSPC: return "ENOSPC";
	case ESPIPE: return "ESPIPE";
	case EROFS: return "EROFS";
	case EMLINK: return "EMLINK";
	case EPIPE: return "EPIPE";
	case EDOM: return "EDOM";
	case ERANGE: return "ERANGE";
	case ENOMSG: return "ENOMSG";
	case EDEADLK: return "EDEADLK";
	case ENOLCK: return "ENOLCK";
	case ENOSTR: return "ENOSTR";
	case ENODATA: return "ENODATA";
	case ETIME: return "ETIME";
	case ENOSR: return "ENOSR";
	case EPROTO: return "EPROTO";
	case EBADMSG: return "EBADMSG";
	case ENOSYS: return "ENOSYS";
	case ENOTEMPTY: return "ENOTEMPTY";
	case ENAMETOOLONG: return "ENAMETOOLONG";
	case ELOOP: return "ELOOP";
	case EOPNOTSUPP: return "EOPNOTSUPP";
	case EPFNOSUPPORT: return "EPFNOSUPPORT";
	case ECONNRESET: return "ECONNRESET";
	case ENOBUFS: return "ENOBUFS";
	case EAFNOSUPPORT: return "EAFNOSUPPORT";
	case EPROTOTYPE: return "EPROTOTYPE";
	case ENOTSOCK: return "ENOTSOCK";
	case ENOPROTOOPT: return "ENOPROTOOPT";
	case ESHUTDOWN: return "ESHUTDOWN";
	case ECONNREFUSED: return "ECONNREFUSED";
	case EADDRINUSE: return "EADDRINUSE";
	case ECONNABORTED: return "ECONNABORTED";
	case ENETUNREACH: return "ENETUNREACH";
	case ENETDOWN: return "ENETDOWN";
	case ETIMEDOUT: return "ETIMEDOUT";
	case EHOSTDOWN: return "EHOSTDOWN";
	case EHOSTUNREACH: return "EHOSTUNREACH";
	case EINPROGRESS: return "EINPROGRESS";
	case EALREADY: return "EALREADY";
	case EDESTADDRREQ: return "EDESTADDRREQ";
	case EMSGSIZE: return "EMSGSIZE";
	case EPROTONOSUPPORT: return "EPROTONOSUPPORT";
	case ESOCKTNOSUPPORT: return "ESOCKTNOSUPPORT";
	case EADDRNOTAVAIL: return "EADDRNOTAVAIL";
	case ENETRESET: return "ENETRESET";
	case EISCONN: return "EISCONN";
	case ENOTCONN: return "ENOTCONN";
	case ETOOMANYREFS: return "ETOOMANYREFS";
	case ENOTSUP: return "ENOTSUP";
	case EILSEQ: return "EILSEQ";
	case EOVERFLOW: return "EOVERFLOW";
	case ECANCELED: return "ECANCELED";
	}
}
