name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        target: [midizephyr]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Checkout submodules
        run: git submodule update --init --depth 1

      - name: West update
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        with:
          args: 'update'

      - name: Build with west for nucleo f429zi
        uses: docker://zmkfirmware/zephyr-west-action-arm:latest
        with:
          args: 'build "-b nucleo_f429zi ${{ matrix.target }}"'

      - name: Create Github release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Publish firmware to release
        id: upload_release_firmware
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/zephyr/zephyr.bin
          asset_name: ${{ matrix.target }}-v${{ github.ref }}.bin
          asset_content_type: application/binary
