name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --depth 1

      - name: Build with west for nucleo f429zi
        uses: "docker://zmkfirmware/zephyr-west-action-arm:latest"
        with:
          args: "build -b nucleo_f429zi midizephyr"
