name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies for Zephyr and West
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git cmake ninja-build gperf dfu-util wget python3-dev python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib g++-multilib
          python3 -m pip install west

      - name: Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.11.3/zephyr-sdk-0.11.3-setup.run
          chmod +x zephyr-sdk-0.11.3-setup.run
          ./zephyr-sdk-0.11.3-setup.run -- -d /opt/zephyr-sdk

      - name: Checkout Zephyr submodule
        run: git submodule update --init

      - name: Build midizephyr for nucleo_f429zi
        run: python3 -m west build -b nucleo_f429zi midizephyr || cat $(find . -name CMakeError.log)
        env:
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
          ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk
