name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install west
      run: pip install west
    - name: build for nucleo_f429zi
      run: west build -b nucleo_f429zi midizephyr
